/**
 * Auto-generated USDC mint address from anchor/usdc-mint-keypair.json
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is regenerated during build from the keypair stored in anchor/usdc-mint-keypair.json
 * Run: pnpm generate-usdc-address
 */

export const LOCALNET_USDC_MINT_ADDRESS = 'C1RWC7Ts6iDfdUGRvEfm8AgQgHHi2BiURcQq9uXULD1w'
