#!/bin/bash

# Extract USDC mint public key from keypair and generate TypeScript constant file
# This script is run during build to ensure the frontend always uses the correct address

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ANCHOR_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
KEYPAIR_PATH="$ANCHOR_DIR/usdc-mint-keypair.json"
OUTPUT_PATH="$ANCHOR_DIR/../src/lib/usdc-mint-address.ts"

if [ ! -f "$KEYPAIR_PATH" ]; then
    echo "Error: USDC mint keypair not found at $KEYPAIR_PATH"
    exit 1
fi

# Get the public key using solana-keygen
MINT_ADDRESS=$(solana-keygen pubkey "$KEYPAIR_PATH" 2>/dev/null)

if [ -z "$MINT_ADDRESS" ]; then
    echo "Error: Could not extract public key from keypair"
    exit 1
fi

# Create TypeScript file with the mint address
cat > "$OUTPUT_PATH" << EOF
/**
 * Auto-generated USDC mint address from anchor/usdc-mint-keypair.json
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file is regenerated during build from the keypair stored in anchor/usdc-mint-keypair.json
 * Run: pnpm generate-usdc-address
 */

export const LOCALNET_USDC_MINT_ADDRESS = '$MINT_ADDRESS'
EOF

echo "✓ Generated USDC mint address: $MINT_ADDRESS"
echo "  Output: $OUTPUT_PATH"
